### ISSUE TITLE
make a way for rads to get newest data

### ISSUE THREAD

**Issue by dcaseykc** [PHSKC-APDE/rads#215] opened 2022-04-14 20:46 UTC
Pull from github? Pull from data?

or just maybe I need to make an hys_current_best thing.

**Comment by dcaseykc** [comment] 2022-05-02 22:35
(so that if the data gets updated, we don't need a re-release. for hys, I've done this by creating a current best.

**Comment by dcolombara** [comment] 2022-07-13 22:35
Duplicate of #235?

get_population and get_data_birth will now always return the most recent data by default. I.e., if I update SQL with birth data through 2021, the get_data_birth will automatically pull 2021 by default without additional changes to the package.

Since we have a solution for hys, birth, and pop -- then I think we can close this issue. Feel free to re-open if I misunderstood the issue.

**Closed** 2022-07-13 22:36 UTC
